modLoader="javafml"
loaderVersion="[43,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/CAS-ual-TY/YgoDuelingMod/issues"

[[mods]]
    modId="ydm"
    version="${file.jarVersion}"
    displayName="Ygo Dueling Mod"
    displayURL="https://github.com/CAS-ual-TY/YgoDuelingMod"
    logoFile="logo.png"
    credits="Mojang and the Minecraft Forge Team"
    authors="CAS_ual_TY"
    description='''
The Ygo Dueling Mod for Minecraft aims to reflect the real life TCG experience in a 3D open world game by not only adding the cards but also the packs and their pull ratios to the game.
Work in progress features:
- All cards and their different variants are available
- Collect them by opening packs, each representing a real life counter part, with accurate rarities and pull ratios
- Chose where to duel, either using a stationairy duel block or having a 3D duel in front of you via duel disks
- It uses a new and intuitive manual dueling simulator that feels more alive (no top-down/bottom-up menus!)
- Make your own server/cards/sets/addons; the mod is open source and the database can be fully customized
'''
