modLoader="javafml"
loaderVersion="[34,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/CAS-ual-TY/YgoDuelingMod/issues"

[[mods]]
    modId="ydm"
    version="${file.jarVersion}"
    displayName="Ygo Dueling Mod"
    displayURL="https://github.com/CAS-ual-TY/YgoDuelingMod"
    logoFile="logo.png"
    credits="Mojang and the Minecraft Forge Team"
    authors="CAS_ual_TY"
    description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed mollis lacinia magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed sagittis luctus odio eu tempus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque volutpat ligula eget lacus auctor sagittis. In hac habitasse platea dictumst. Nunc gravida elit vitae sem vehicula efficitur. Donec mattis ipsum et arcu lobortis, eleifend sagittis sem rutrum. Cras pharetra quam eget posuere fermentum. Sed id tincidunt justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit."
